services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    # container_name: watchtracker-backend
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    # container_name: watchtracker-frontend
    ports:
      - "${FRONTEND_PORT:-3000}:80"
    depends_on:
      - backend
    restart: unless-stopped
